---
Title: "Readme"
Author: "Ricardo Costa"
Date: "July 27, 2014"
Output: html_document
---

## Getting and Cleaning Data Programming Assignment  
### Description  
One of the most exciting areas in all of data science right now is wearable computing - see for example an article by [clicking here][http://www.insideactivitytracking.com/data-science-activity-tracking-and-the-battle-for-the-worlds-top-sports-brand/]. Companies like Fitbit, Nike, and Jawbone Up are racing to develop the most advanced algorithms to attract new users. The data linked to from the course website represent data collected from the accelerometers from the Samsung Galaxy S smartphone. A full description is available at the site where the data was obtained by [clicking here][http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones].  
 
The purpose of this project is to demonstrate your ability to collect, work with, and clean a data set. The goal is to prepare tidy data that can be used for later analysis. It generates tidy data sets as described below: 

- Merges the training and the test sets to create one data set.
- Extracts only the measurements on the mean and standard deviation for each measurement. 
- Uses descriptive activity names to name the activities in the data set
- Appropriately labels the data set with descriptive variable names. 
- Creates a second, independent tidy data set with the average of each variable for each activity and each subject. 

### Environment 
The evironment used for this script is below:  

- platform       x86_64-apple-darwin10.8.0     
- arch           x86_64                        
- os             darwin10.8.0                  
- system         x86_64, darwin10.8.0                                               
- major          3                             
- minor          1.0                           
- year           2014                          
- month          04                            
- day            10                            
- svn rev        65387                         
- language       R                             
- version.string R version 3.1.0 (2014-04-10)  
- nickname       Spring Dance  

